### ISSUE TITLE
"AI Suite"-button missing in RTE - "Content Modification"-feature

### ISSUE THREAD

**Issue by richardkrikler** [autodudesde/ai-suite#5]
**Problem description:**
Feature: "Content Modification"
The "AI Suite"-button is missing in the RTE (using default configuration) in TYPO3 version 11.
In TYPO3 version 12 the button is visible, but not clickable & results with an error message in the browser console (see screenshot).
All other AI-Suite features work.
I could not find any documentation on how to configure the behaviour (enabling or disabling the RTE button, e.g. with `extraPlugins` in the rte config).
The tested content element is a default TYPO3 text element.
The sys_language_uid field is 0. Installation site language is German de_AT.UTF-8 with ID 0 (but also tested with en_US.utf8).
Autodudes Docs: https://www.autodudes.de/documentation/ai-suite/en/for-editors/modification-of-content

![387257279-1cbbf785-0a8a-4add-b4f2-1cbeb8259fdb](https://github.com/user-attachments/assets/c4ad18db-2dd6-46b8-b7ca-be8887266f14)

**Setup Description:**
Tested in the newest version of Edge & Chrome.
Tested with following TYPO3 versions (both newest available & composer based): 11 & 12 (v11 in docker & ddev setup, v12 in ddev setup)
Used ai_suite version: v11.3.1, v12.6.1

**Comment by passionweb-manuel-schnabel** [comment]
Hey @richardkrikler,

thanks for reporting the issue. 

The CKEditor5 plugin is only available in TYPO3 v12 and above. For TYPO3 v11 there is unfortunately currently no CKEditor4 plugin available.

We have tried to reproduce your problem with the given description above. Sounds like there is a (clientside) problem while fetching the libraries. Could you please send us an additional screenshot from the network tab? There must be a request like "https://ai-suite.ddev.site/typo3/ajax/generate/ckeditor-libraries". Could ytou please send us the response from that request? Sometimes (e.g. if we switch the network or have a bad network connection) we faced out similar problems.

If you want to modify the permissions for editors you can find more information here: https://www.autodudes.de/documentation/ai-suite/en/for-administrators/permission-management. The CKEditor plugin gets integrated via an event because we can't access your RTE yaml configuration presets.

Thanks for your help in advance!

**Comment by richardkrikler** [comment]
Hi :wave:

Thank you for providing the link to the Permission-Management Documentation!

It would be nice to display some information about feature availability on different TYPO3 versions (probably not only in the documentation, but also on the features-page https://www.autodudes.de/en/features/). It was not clear to me that the RTE Content Modification Feature is only available in v12 and later. Thanks for clarifying.

I tested the feature again in TYPO3 v12. Here are the screenshots. Apparently the libraries could not be fetched?
There isn't anything in the logs. typo3/cms-rte-ckeditor: v12.4.23
![SCR-20241122-ikuc](https://github.com/user-attachments/assets/00b3b045-a485-4f81-9ce4-ee59b17b571e)
![SCR-20241122-ikxt](https://github.com/user-attachments/assets/3892834e-13f0-4126-855d-10bc603d3518)
![SCR-20241122-ilhs](https://github.com/user-attachments/assets/09fe49d6-624e-4d96-a73c-f9fff4375bf3)

**Comment by krausandre** [comment]
Hi @richardkrikler,

thank you very much for your efforts and patience!

Well, since the [feature page](https://www.autodudes.de/en/features/) just gives and very general overview and not being this detailed, I would prefer to mention this in the documentation, [where exactly the CKEditor feature is described](https://www.autodudes.de/documentation/ai-suite/en/for-editors/modification-of-content). Do you agree? 

And maybe your behavior is related to [this issue](https://www.autodudes.de/documentation/ai-suite/en/known-problems#c315)? 
I had also problems after updating from TYPO3 v12.4.15 to v12.4.23, but clearing all caches resolved this for me. I guess, you already cleared all caches? Even the browser caches?

Best regards

**Comment by richardkrikler** [comment]
I definitely agree with you on where to place the information about the minimum TYPO3 version for this feature.

The feature works for me too after adding the Autodudes API key 🎉  (so no problems there - Thank you!)

With the latter part of my response, I just wanted to ask if an Autodudes subscription is needed when I provide my own OpenAI key?
I wanted to try that too, because it is described in the documentation. I left the field for the Autodudes API key empty & only filled the OpenAI key in the "Bring your Own Keys" section of the settings.

> Another thing I wanted to try, was the "Bring your Own Keys" setting with an OpenAI API-Key. The problem is that keys from other services are not being used in the extension. I can provide one in the settings, but in the end it will not be used & errors like the previous described happen (if no Autodudes key is provided).
> "_This area is important for all users with a subscription. Here you must deposit your own API key, which should be used in connection with your respective license key._" → does this mean that I need an Autodudes [subscription](https://www.autodudes.de/en/TYPO3-AI-Suite-Subscription/AD10006) to use my own keys?
